import { adminList,lineNumlist,logList } from '@/service/index'
export const admin = {
    state:{
       adminList:[],//管理员列表
       lineNumList:[],//线路号列表
       loading:false,
       adminLog:[],
       debugLog:[],
       startKey:{},
       lineLog:[],
       merchantLog:[]
    },
    mutations:{
        changeAdminList(state,{params}){
            state.adminList=params
        },
        changeLineNumList(state,{params}){
            state.lineNumList=params
        },
        updateLoading(state,{params}){
            state.loading=params
        },//log
        //全部adminlog
        // updateAllAdminLog(state,{params}){
        //     state.allAdminLog.push(params);
        //     state.allAdminLog = _.uniqWith(state.allAdminLog, _.isEqual);
        // },  
        changeAdminLog(state,{params}){
            state.adminLog=params
        },
        changeStartKey(state,{params}){
            state.startKey=params
        },
        changeDebugLog(state,{params}){
            state.debugLog=params
        },
        changeLineLog(state,{params}){
            state.lineLog=params
        },
        changeMerchantLog(state,{params}){
            state.merchantLog=params
        }
    },
    actions:{
      getAdminList({commit},params){
        adminList(params).then(res=>{
            if(res.code==0){
                commit('changeAdminList',{params:res.payload})
                commit('updateLoading',{params:false})
            }
        })
      },
      getLineNumList({commit},params){
          lineNumlist(params).then(res=>{
            if(res.code==0){
                commit('changeLineNumList',{params:res.payload.Items})
                commit('updateLoading',{params:false})
            }
          })
      },
      getAdminLog({commit},params){
        commit('updateLoading',{params:true})
        return logList(params).then(res=>{
            if(res.code==0){
                commit('changeAdminLog',{params:res.payload.Items});
                commit('changeStartKey',{params:res.payload.LastEvaluatedKey})
                commit('updateLoading',{params:false})
            }
        })
      },
      getDebugLog({commit},params){
        commit('updateLoading',{params:true})
          logList(params).then(res=>{
            if(res.code==0){
                commit('changeDebugLog',{params:res.payload.Items})
                commit('changeStartKey',{params:res.payload.LastEvaluatedKey})
                commit('updateLoading',{params:false})
            }              
          })
      },
      getMerchantLog({commit},params){
        commit('updateLoading',{params:true})
          logList(params).then(res=>{
              commit('changeMerchantLog',{params:res.payload.Items})
              commit('changeStartKey',{params:res.payload.LastEvaluatedKey})
              commit('updateLoading',{params:false})
              
          })
      },
      getLineLoginLog({commit},params){
        commit('updateLoading',{params:true})
          logList(params).then(res=>{
              if(res.code==0){
                  commit('changeLineLog',{params:res.payload.Items})
                  commit('changeStartKey',{params:res.payload.LastEvaluatedKey})
                  commit('updateLoading',{params:false})
              }
          })
      },
    }
}